name: Coinglass Full T+1

on:
  schedule:
    - cron: '20 2 * * *'  # 02:20 UTC
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: coinglass-full
  cancel-in-progress: true

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 420
    env:
      CG_API_KEY: ${{ secrets.CG_API_KEY }}
      DATABASE_URL: ${{ secrets.SUPABASE_DB_URL }}
      CG_QPM: '80'
      START_DATE: '2015-01-01'  # 你原本就是全量
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Force IPv4 to Supabase
        env:
          DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        shell: bash
        run: |
          set -euo pipefail
          HOST=$(python - <<'PY'
          import os, urllib.parse
          u = urllib.parse.urlparse(os.environ['DB_URL'])
          print(u.hostname or '')
          PY
          )
          IPV4=$(getent ahostsv4 "$HOST" | awk '{print $1; exit}')
          [ -n "$IPV4" ] || { echo "Cannot resolve IPv4 for $HOST"; exit 1; }
          echo "PGHOSTADDR=$IPV4" >> "$GITHUB_ENV"

      - name: Run Dataupsert (Full backfill)
        env:
          CG_API_KEY: ${{ secrets.CG_API_KEY }}
          DATABASE_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: python Dataupsert.py
