name: Coinglass Fast T+0
on:
  schedule:
    - cron: '5 */2 * * *'   # 每 2 小時 UTC :05
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    env:
      CG_API_KEY: ${{ secrets.CG_API_KEY }}
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      CG_QPM: '60'
      CG_TIMEOUT: '90'
      CG_API_LIMIT: '4500'
      CG_EXCHANGES: 'Binance'
      CG_EXLISTS: 'Binance,OKX,Bybit'
      CG_COINS: 'BTC,ETH,XRP,BNB,SOL,DOGE,ADA'
      # 只跑會影響日內觀察/指標的任務，縮短時長
      TASKS: 'futures_candles_1d,spot_candles_1d,oi_agg_1d,oi_stable_1d,oi_coinm_1d,funding_1d,long_short_1d,liquidation_1d,orderbook_agg_futures_1d,taker_vol_agg_futures_1d,coinbase_premium_index_1d,bitfinex_margin_long_short_1d,borrow_interest_rate_1d'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt
      - name: 只抓近 4 天（含昨天），快補
        run: |
          echo "START_DATE=$(date -u -d '4 days ago' +%F)" >> $GITHUB_ENV
          echo "END_DATE=$(date -u -d 'yesterday' +%F)"   >> $GITHUB_ENV
      - run: python Dataupsert.py
