name: Coinglass Fast T+0

on:
  schedule:
    - cron: '1 0 * * *'     # 00:01 UTC
    - cron: '10 0 * * *'    # 00:10 UTC
  workflow_dispatch:

permissions:
  contents: read

env:
  CG_API_KEY: ${{ secrets.CG_API_KEY }}
  DATABASE_URL: ${{ secrets.SUPABASE_DB_URL }}
  CG_QPM: '60'     # 較保守，避免 API 429

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    concurrency:
      group: coinglass-fast
      cancel-in-progress: false

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: pip

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Date range (patch last 10d)
        run: echo "START_DATE=$(date -u -d '10 days ago' +%F)" >> $GITHUB_ENV

      - name: Force IPv4 & append hostaddr to DSN
        shell: bash
        run: |
          python - <<'PY'
          import os, urllib.parse, socket
          dsn=os.environ['DATABASE_URL']
          u=urllib.parse.urlparse(dsn)
          host=u.hostname; port=u.port or 5432
          ip=socket.getaddrinfo(host, port, family=socket.AF_INET)[0][4][0]
          q=urllib.parse.parse_qsl(u.query, keep_blank_values=True)
          q.append(('hostaddr', ip))
          new_q=urllib.parse.urlencode(q)
          new_dsn=urllib.parse.urlunparse((u.scheme, u.netloc, u.path, u.params, new_q, u.fragment))
          open(os.environ['GITHUB_ENV'],'a').write(f"DATABASE_URL={new_dsn}\n")
          PY

      - name: DB smoke test
        run: |
          python - <<'PY'
          import os, psycopg2
          c=psycopg2.connect(os.environ['DATABASE_URL'])
          cur=c.cursor(); cur.execute('select 1'); cur.fetchone(); c.close()
          PY

      - name: Run Dataupsert (Fast)
        run: python Dataupsert.py
