name: Coinglass Full T+1
on:
  schedule:
    - cron: '35 0 * * *'   # 每天 00:35 UTC
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    concurrency:
      group: coinglass-full
      cancel-in-progress: false
    env:
      CG_API_KEY: ${{ secrets.CG_API_KEY }}
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      CG_QPM: '80'
      CG_TIMEOUT: '120'
      CG_API_LIMIT: '4500'
      CG_EXCHANGES: 'Binance'
      CG_EXLISTS: 'Binance,OKX,Bybit'
      CG_COINS: 'BTC,ETH,XRP,BNB,SOL,DOGE,ADA'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: pip install -r requirements.txt
      - name: 從歷史抓到昨天，做日更校正
        run: |
          echo "START_DATE=2015-01-01" >> $GITHUB_ENV
          echo "END_DATE=$(date -u -d 'yesterday' +%F)" >> $GITHUB_ENV
      - run: python Dataupsert.py
