name: features_1d

on:
  schedule:
    - cron: "10 1 * * *"    # 每日 01:10 UTC；可調
  workflow_dispatch: {}

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      PGSSLMODE: require
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Set up job
        run: echo "start"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test DB connection
        run: |
          python scripts/test_conn.py

      - name: Run features pipeline
        env:
          DAYS: "7"      # 只上傳近 7 天
        run: |
          PYTHONPATH=. python -m src.cli.build_features_labels
