name: features_1d

on:
  workflow_dispatch:
    inputs:
      days:
        description: "更新最近幾天"
        required: false
        default: "7"
      end_date:
        description: "END_DATE (UTC, YYYY-MM-DD)，預設昨天"
        required: false
        default: ""
  schedule:
    - cron: "5 2 * * *"   # 每天 02:05 UTC 跑一次

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      DATABASE_URL: ${{ secrets.SUPABASE_DB_URL }}  # 給任何舊程式使用
      DAYS: ${{ inputs.days || '7' }}
      END_DATE: ${{ inputs.end_date }}

    steps:
      - name: Set up job
        run: echo "Starting…"

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Map DSN for legacy code
        run: |
          echo "PG_DSN=${SUPABASE_DB_URL}" >> $GITHUB_ENV

      - name: Test DB connection
        run: python scripts/test_conn.py

      - name: Run features pipeline
        env:
          DAYS: ${{ env.DAYS }}
          END_DATE: ${{ env.END_DATE }}
        run: bash scripts/run_features_1d.sh
