name: Daily Coinglass Ingest

on:
  schedule:
    - cron: "20 2 * * *"        # 每日 02:20 UTC
  workflow_dispatch:
    inputs:
      start_date:
        description: "YYYY-MM-DD；空=自動最近14天"
        required: false
      end_date:
        description: "YYYY-MM-DD；空=昨天(UTC)"
        required: false

permissions:
  contents: read

concurrency:
  group: coinglass-ingest
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 180

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Compute date window
        run: |
          # 14 天滾動視窗；可在手動觸發時覆蓋
          if [ -n "${{ github.event.inputs.start_date }}" ]; then
            echo "START_DATE=${{ github.event.inputs.start_date }}" >> $GITHUB_ENV
          else
            echo "START_DATE=$(date -u -d '14 days ago' +%F)" >> $GITHUB_ENV
          fi
          if [ -n "${{ github.event.inputs.end_date }}" ]; then
            echo "END_DATE=${{ github.event.inputs.end_date }}" >> $GITHUB_ENV
          else
            echo "END_DATE=$(date -u -d 'yesterday' +%F)" >> $GITHUB_ENV
          fi
          echo "Using START_DATE=$START_DATE END_DATE=$END_DATE"

      - name: Ingest to Supabase
        env:
          CG_API_KEY:        ${{ secrets.CG_API_KEY }}
          SUPABASE_DB_URL:   ${{ secrets.SUPABASE_DB_URL }}
          CG_QPM: "80"
          CG_API_LIMIT: "4500"
          CG_EXCHANGES: "Binance"
          CG_EXLISTS: "Binance,OKX,Bybit"
          CG_COINS: "BTC,ETH,XRP,BNB,SOL,DOGE,ADA"
          START_DATE: ${{ env.START_DATE }}
          END_DATE:   ${{ env.END_DATE }}
        run: |
          python Dataupsert.py
